import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { getRandom } from '../utils/random_array_ele';
import { fetchAllBooks } from '../helpers/from-end/products_prop_funcs';

import Banner from '../components/Functional/Home/Banner/Banner';
import ProductShowcase from '../components/Functional/Home/ProductShowcase/ProductShowcase';
import Quote from '../components/Functional/Home/Quote/Quote';
import CategoryNavigation from '../components/Functional/Home/CategoryNavigation/CategoryNavigation';

export default function Home({ popularBooks }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bookasura</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <ProductShowcase popularBooks={popularBooks} />
        <Quote />
        <CategoryNavigation />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const {books} = await fetchAllBooks();

  const popularBooks = getRandom(books, 4);

  return {
    props: {
      popularBooks,
      books,
    },
    revalidate: 86400,
  };
};
