import Head from 'next/head';
import axios from 'axios';
import { useSelector, useDispatch } from 'react-redux';

import styles from '../styles/Home.module.css';

import Book from '../models/front_end/product';
import { getRandom } from '../utils/random_array_ele';

import Banner from '../components/Functional/Home/Banner/Banner';
import ProductShowcase from '../components/Functional/Home/ProductShowcase/ProductShowcase';
import Quote from '../components/Functional/Home/Quote/Quote';
import CategoryNavigation from '../components/Functional/Home/CategoryNavigation/CategoryNavigation';

import { fetchAllBooks } from '../context/actions/books_actions';
import { requestUrl } from '../db/domain_url';

export default function Home({popularBooks}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bookasura</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <ProductShowcase popularBooks={popularBooks}/>
        <Quote />
        <CategoryNavigation />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const response = await axios.get(requestUrl('api/products'));
  const books = response.data.map(
    (book) =>
      new Book(
        book._id,
        book.name,
        book.price,
        book.description,
        book.category.name,
        book.imageUrl,
        book.inventory.quantity,
      ).getBook(),
  );

  const popularBooks = getRandom(books, 4);

  return {
    props: {
      popularBooks
    },
    revalidate: 86400,
  };
};
